# Generated by Django 4.2.4 on 2023-08-07 14:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Why_choose_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('list_items', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AddField(
            model_name='about_model',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
