# Generated by Django 4.2.4 on 2023-08-07 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_why_choose_us_about_model_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_model',
            name='list_items',
        ),
        migrations.CreateModel(
            name='About_model_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(max_length=200)),
                ('dynamic_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.about_model')),
            ],
        ),
    ]
