# Generated by Django 4.2.4 on 2023-08-07 14:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_remove_about_model_list_items_about_model_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_model',
            name='list_items',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.DeleteModel(
            name='About_model_list',
        ),
    ]
