# Generated by Django 4.2.4 on 2023-08-07 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_about_model_list_items_delete_about_model_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_model',
            name='list_items',
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.about_model')),
            ],
        ),
        migrations.AddField(
            model_name='about_model',
            name='list_items',
            field=models.ManyToManyField(blank=True, to='my_app.listitem'),
        ),
    ]
