# Generated by Django 4.2.4 on 2023-08-07 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_remove_about_model_list_items_listitem_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListItem',
            new_name='About_List_Item',
        ),
    ]
