# Generated by Django 4.2.4 on 2023-08-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_rename_listitem_about_list_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('button_link', models.CharField(max_length=200)),
                ('button_vid', models.CharField(max_length=200)),
            ],
        ),
    ]
