# Generated by Django 4.2.4 on 2023-08-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_home_model_image_alter_about_model_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
