# Generated by Django 4.2.4 on 2023-08-08 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_alter_about_model_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home_model',
            name='button_link',
        ),
    ]
