# Generated by Django 4.2.4 on 2023-08-08 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_remove_why_choose_us_list_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='why_choose_us',
            old_name='sub_descripton',
            new_name='sub_description',
        ),
    ]
