# Generated by Django 4.2.4 on 2023-08-08 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_rename_sub_descripton_why_choose_us_sub_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Why_choose_us',
            new_name='Why_choose_us_model',
        ),
    ]
