# Generated by Django 4.2.4 on 2023-08-08 13:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_rename_why_choose_us_why_choose_us_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icon/')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
    ]
