# Generated by Django 4.2.4 on 2023-08-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_service_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_model',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icon/services'),
        ),
    ]
