# Generated by Django 4.2.4 on 2023-08-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_footer_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_model',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
